# Generated by Django 2.2.16 on 2022-07-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_ingredient',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('product', 'amount'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_product'),
        ),
    ]
