# Generated by Django 2.2.16 on 2022-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
