# Generated by Django 2.2.16 on 2022-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220731_1516'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_favorite_list'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('product', 'amount'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_product'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('owner',), name='unique_shopping_list'),
        ),
    ]
